import { ImageResponse } from "next/og";
import { formatBps, formatCadenceHours, formatUsd } from "@/lib/edge";
import { getCachedSnapshot } from "@/lib/server-snapshot";

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";
export const alt = "Perp Verdict source-stamped funding truth card";
export const dynamic = "force-dynamic";
export const revalidate = 15;

function pairLabel(symbol: string) { return symbol.toUpperCase().replace("USDT", " / USDT"); }
function sourceTime(sources: { sourceTimestamp: string }[]) { return sources.map((source) => source.sourceTimestamp).filter(Boolean).sort().at(-1)?.slice(11, 16) ?? "receipt"; }

export default async function Image({ params }: { params: Promise<{ pair: string }> }) {
  const { pair } = await params;
  const result = await getCachedSnapshot(pair);
  if (result.kind === "unavailable") return new ImageResponse(<div style={{ background: "#f5f5f0", color: "#16231f", display: "flex", flexDirection: "column", height: "100%", padding: "56px", width: "100%" }}><span style={{ color: "#2e7d4f", fontSize: 20, fontWeight: 700, letterSpacing: 4 }}>PERP VERDICT</span><span style={{ fontSize: 64, fontWeight: 700, marginTop: 56 }}>{pairLabel(result.symbol)}</span><span style={{ color: "#c84c48", fontSize: 30, fontWeight: 700, marginTop: 24 }}>LIVE SNAPSHOT UNAVAILABLE</span><span style={{ color: "#65716b", fontSize: 23, marginTop: 18 }}>Fail-closed · no demo fallback · read only</span><span style={{ borderTop: "2px solid #d9dfd8", fontSize: 17, marginTop: "auto", paddingTop: 17 }}>Public source validation failed: {result.reason}</span></div>, { ...size });
  const positive = result.model.modeledNetBps > 0;
  return new ImageResponse(<div style={{ background: "#f5f5f0", color: "#16231f", display: "flex", flexDirection: "column", height: "100%", padding: "48px 56px", width: "100%" }}><div style={{ alignItems: "center", display: "flex", justifyContent: "space-between" }}><span style={{ color: "#2e7d4f", fontSize: 20, fontWeight: 700, letterSpacing: 4 }}>PERP VERDICT</span><span style={{ border: "1px solid #c84c48", color: "#c84c48", fontSize: 15, fontWeight: 700, letterSpacing: 2, padding: "10px 14px" }}>MODELED / NOT EXECUTABLE</span></div><div style={{ display: "flex", flexDirection: "column", marginTop: 44 }}><span style={{ color: "#65716b", fontSize: 20, letterSpacing: 2 }}>LIVE FUNDING TRUTH CARD</span><span style={{ fontSize: 72, fontWeight: 700, letterSpacing: -4, marginTop: 10 }}>{pairLabel(result.symbol)}</span><span style={{ color: "#65716b", fontSize: 24, marginTop: 8 }}>{result.model.higherFundingVenue} short → {result.model.higherFundingVenue === "Binance" ? "Bybit" : "Binance"} long</span></div><div style={{ display: "flex", gap: 56, marginTop: 44 }}><div style={{ display: "flex", flexDirection: "column" }}><span style={{ color: "#65716b", fontSize: 16, letterSpacing: 1 }}>RAW DIFFERENTIAL</span><span style={{ fontSize: 38, fontWeight: 700, marginTop: 7 }}>{formatBps(result.model.grossFundingBps)}</span></div><div style={{ display: "flex", flexDirection: "column" }}><span style={{ color: "#65716b", fontSize: 16, letterSpacing: 1 }}>MODELED NET</span><span style={{ color: positive ? "#167b51" : "#c84c48", fontSize: 38, fontWeight: 700, marginTop: 7 }}>{formatBps(result.model.modeledNetBps)}</span></div><div style={{ display: "flex", flexDirection: "column" }}><span style={{ color: "#65716b", fontSize: 16, letterSpacing: 1 }}>CADENCE</span><span style={{ fontSize: 38, fontWeight: 700, marginTop: 7 }}>{formatCadenceHours(result.cadence.binanceHours)} = {formatCadenceHours(result.cadence.bybitHours)}</span></div></div><div style={{ borderTop: "2px solid #d9dfd8", display: "flex", flexDirection: "column", fontSize: 17, gap: 6, marginTop: "auto", paddingTop: 17 }}><span>Fees {result.model.roundTripFeeBps.toFixed(1)} · Depth {result.model.depthSlippageBps.toFixed(1)} · Transfer {result.model.transferReserveBps.toFixed(1)} · Buffer {result.model.liquidationBufferBps.toFixed(1)} bp · {formatUsd(result.model.notionalUsd)}</span><span>Captured {result.capturedAt.slice(0, 16).replace("T", " ")} UTC · venue times B {sourceTime(result.sources.binance)} / Y {sourceTime(result.sources.bybit)} · {result.snapshotId.slice(0, 24)}</span></div></div>, { ...size });
}
